version: '3'

services:
  service1:
    build: ./rooms
    ports:
      - "3000:7777"
  service2:
    build: ./books
    ports:
      - "3001:4545"
  service3:
    build: ./customers
    ports:
      - "3002:5555"
  service4:
    build: ./orders
    ports:
      - "3003:8080"

networks:
  default:
    external:
      name: cloud-network
